services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=subscription
      - DB_PASSWORD=123
      - DB_NAME=subscriptions
      - DB_SSLMODE=disable

  db:
    # Версия 16, т.к. с latest работает последняя версия докера, а он не поддерживает свой API в GoLand
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: subscription
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: subscriptions
